function new-site-sails -a name -d "Generate new sails application" 
  switch "$name"
  case ''
    crow error "Usage: new-site-html <name>"
  case '*'
    cd /tardis/sites/
    sails new $name
    cd /tardis/sites/$name

    echo "# GENERATED by new-site-sails" > config/nginx.conf
    echo "server {" >> config/nginx.conf
    echo " listen 80;" >> config/nginx.conf
    echo -s " server_name " $name "." (hostname) ";" >> config/nginx.conf
    echo -s " error_page 404 /404.html"
    echo -s " error_page 500 501 502 503 504 /50x.html"
    echo -s " root /tardis/sites/" $name "/public;" >> config/nginx.conf
    echo "}" >> config/nginx.conf

    crow notify "Restarting webserver"
    rweb
  
    crow success "Site ready"  
    editor views/home/index.ejs
  end
end
